sudo: required
services:
  - docker
before_install:
  # decryption key decrypts the encrypted ket and creates a service-account.json file
  - openssl aes-256-cbc -K $encrypted_3a9098f032f0_key -iv $encrypted_3a9098f032f0_iv -in dummy-service-account.json.enc -out dummy-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # file is created in travis local fine system, this key can access any project
  - gcloud auth activate-service-account --key-file service-account.json
  # specify which project needs to be worked upon <specify the id>
  - gcloud config set project <the_project_id>
  # set zone
  - gcloud config set compute/zone <zone_name_of_cluster>
  # specify the cluster
  - gcloud container clusters get-credentials <cluster_name>
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # run tests
  - docker build -t kumarvdocker/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true kumarvdocker/react-test npm test
  