apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
# ReadWriteOnce - can be used by single node
# ReadOnlyMany - Multiple node can read from this
# ReadWriteMany - read and write by many nodes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
